export const operatorPage = `<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex,nofollow">
  <title>Famicom Game Drop | 管理者</title>
  <style>
    :root{color-scheme:light;--bg:#f5f4ee;--paper:#fffefa;--ink:#183128;--muted:#52645c;--green:#123b2e;--line:#d7dfd5;--gold:#f8cc6b;--red:#9b332a}
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 system-ui,-apple-system,"Segoe UI",sans-serif}
    button,input{font:inherit}button{cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}a{color:inherit;text-underline-offset:.18em}
    :focus-visible{outline:3px solid #d77b28;outline-offset:3px}.shell{width:min(1000px,calc(100% - 32px));margin:auto}
    header{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:24px 0}.brand{font-weight:850;text-decoration:none;letter-spacing:-.03em}
    .brand span{display:inline-grid;place-items:center;width:38px;height:38px;margin-right:9px;border-radius:11px;background:var(--gold);font-size:.85rem}
    .lang{display:flex;gap:4px}.lang button{border:1px solid var(--line);background:var(--paper);border-radius:999px;padding:5px 12px;color:var(--muted)}.lang button[aria-pressed=true]{background:var(--green);color:white}
    main{padding:40px 0 80px}.eyebrow{color:#357153;text-transform:uppercase;letter-spacing:.13em;font-weight:850;font-size:.78rem}
    h1{font-size:clamp(2.3rem,5vw,4.2rem);line-height:1.1;letter-spacing:-.06em;margin:10px 0 18px}.lead{max-width:65ch;color:var(--muted);margin-bottom:30px}
    .card{background:var(--paper);border:1px solid var(--line);border-radius:22px;padding:clamp(20px,4vw,32px);box-shadow:0 12px 34px #1831280a;margin-bottom:18px}
    h2{margin:0 0 8px;font-size:1.35rem;letter-spacing:-.03em}p{margin:0 0 14px}.muted{color:var(--muted)}
    label{display:block;font-weight:750;margin:0 0 7px}input[type=password]{width:min(100%,460px);padding:13px;border:1px solid #9eb4a6;border-radius:10px;background:#fff}
    .row{display:flex;gap:10px;flex-wrap:wrap;align-items:center}.button{border:0;border-radius:11px;padding:11px 18px;background:var(--green);color:white;font-weight:800}.button.secondary{background:#e5f0e8;color:var(--green)}.button.danger{background:#fff0ea;color:var(--red)}
    .note{padding:15px 17px;border:1px solid #e9d391;border-radius:13px;background:#fff8dc;color:#624e1e}.error{color:var(--red)}
    .facts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:22px 0}.fact{border:1px solid var(--line);border-radius:13px;padding:13px;background:#f8faf6}.fact strong{display:block;font-size:1.25rem}.fact span{font-size:.8rem;color:var(--muted)}
    .queue{display:grid;gap:9px;margin-top:18px}.queue-item{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:14px;border:1px solid var(--line);border-radius:12px;background:#fafbf8}.queue-item p{margin:0}.queue-item small{color:var(--muted)}
    .queue-item button{border:1px solid #e2b6aa;border-radius:8px;background:#fff7f4;color:var(--red);padding:6px 9px;font-size:.8rem;font-weight:750}
    [hidden]{display:none!important}@media(max-width:700px){.facts{grid-template-columns:repeat(2,minmax(0,1fr))}main{padding-top:20px}.queue-item{align-items:flex-start}}
  </style>
</head>
<body>
  <header class="shell"><a class="brand" href="/"><span>FC</span>Famicom Game Drop</a><div class="lang" role="group" aria-label="Language / 言語"><button type="button" id="ja" aria-pressed="true">日本語</button><button type="button" id="en" aria-pressed="false">EN</button></div></header>
  <main class="shell"><p class="eyebrow" data-t="eyebrow">展示スタッフ用</p><h1 data-t="title">次のゲームを送る。</h1><p class="lead" data-t="lead">来場者のゲームは受付リストで待機します。プレイの区切りで「次の1件を送る」を押してください。カートリッジが受信して切り替えます。</p>
    <section class="card" id="login"><h2 data-t="loginTitle">管理者として接続</h2><p class="muted" data-t="loginHelp">管理用トークンはこの画面の間だけ使い、ブラウザには保存しません。</p><form id="loginForm"><label for="token" data-t="token">管理用トークン</label><div class="row"><input id="token" type="password" autocomplete="off" required><button class="button" type="submit" data-t="connect">接続</button></div></form><p class="error" id="loginError" role="alert" hidden></p></section>
    <div id="dashboard" hidden>
      <section class="card"><div class="row" style="justify-content:space-between"><h2 data-t="statusTitle">展示の状態</h2><button class="button secondary" id="refresh" type="button" data-t="refresh">更新</button></div><div class="facts"><div class="fact"><strong id="device">—</strong><span data-t="deviceLabel">カートリッジ</span></div><div class="fact"><strong id="power">—</strong><span data-t="powerLabel">本体電源</span></div><div class="fact"><strong id="queueCount">—</strong><span data-t="queueLabel">待機中</span></div><div class="fact"><strong id="runState">—</strong><span data-t="runLabel">キュー</span></div></div><p class="note" data-t="safety">電源ONのまま送るとゲームは一度止まります。切替完了を確認してから、ファミコン本体のRESETを押してください。実機安全試験は別途必要です。</p></section>
      <section class="card"><h2 data-t="controlTitle">キューを進める</h2><p class="muted" data-t="controlHelp">1回の操作で先頭の1件だけ実機に解放します。処理中は次の件を送れません。</p><div class="row"><button class="button" id="advance" type="button" data-t="advance">次の1件を送る</button><button class="button secondary" id="pause" type="button">—</button></div><p id="actionFeedback" role="status" aria-live="polite"></p></section>
      <section class="card"><h2 data-t="waitingTitle">受付リスト</h2><p class="muted" data-t="waitingHelp">ROM本体は表示しません。お名前とコメントは展示スタッフだけに表示されます。</p><div class="queue" id="queue" aria-live="polite"></div></section>
      <section class="card"><h2 data-t="galleryTitle">公開ギャラリー</h2><p class="muted" data-t="galleryHelp">掲載だけを取り下げます。受付済みのROMやプレイ待ちは取り消しません。</p><div class="queue" id="galleryQueue" aria-live="polite"></div></section>
    </div>
  </main>
  <script>
    const copy={ja:{eyebrow:"展示スタッフ用",title:"次のゲームを送る。",lead:"来場者のゲームは受付リストで待機します。プレイの区切りで「次の1件を送る」を押してください。カートリッジが受信して切り替えます。",loginTitle:"管理者として接続",loginHelp:"管理用トークンはこの画面の間だけ使い、ブラウザには保存しません。",token:"管理用トークン",connect:"接続",statusTitle:"展示の状態",refresh:"更新",deviceLabel:"カートリッジ",powerLabel:"本体電源",queueLabel:"待機中",runLabel:"キュー",safety:"電源ONのまま送るとゲームは一度止まります。切替完了を確認してから、ファミコン本体のRESETを押してください。実機安全試験は別途必要です。",controlTitle:"キューを進める",controlHelp:"1回の操作で先頭の1件だけ実機に解放します。処理中は次の件を送れません。",advance:"次の1件を送る",waitingTitle:"受付リスト",waitingHelp:"ROM本体やアップロード者の情報はこの画面に表示しません。",online:"接続中",offline:"未接続",on:"ON",off:"OFF",paused:"停止中",running:"受付中",pause:"停止する",resume:"再開する",empty:"受付待ちのゲームはありません。",waiting:"管理者待ち",sent:"実機へ送信中",claimed:"実機が受信中",downloaded:"切替中",deferred:"安全待ち",cancel:"取り消す",cancelConfirm:"この受付を取り消しますか？",advanceDone:"先頭の1件を実機へ送るよう指示しました。",actionError:"操作できませんでした。状態を更新して再確認してください。",authError:"トークンを確認してください。",networkError:"接続できません。後で再試行してください。"},en:{eyebrow:"Exhibition staff",title:"Send the next game.",lead:"Visitor games wait in the queue. Press Send next between plays; the cartridge will receive and switch to that game.",loginTitle:"Connect as operator",loginHelp:"The operator token is used only while this page is open. It is not saved in the browser.",token:"Operator token",connect:"Connect",statusTitle:"Exhibition status",refresh:"Refresh",deviceLabel:"Cartridge",powerLabel:"Console power",queueLabel:"Waiting",runLabel:"Queue",safety:"Sending while power is on will pause the game. After the changeover finishes, press RESET on the Famicom. Real-board safety testing is still required.",controlTitle:"Advance the queue",controlHelp:"One press releases only the first waiting entry. You cannot send another while one is in progress.",advance:"Send next game",waitingTitle:"Visitor queue",waitingHelp:"ROM bytes and uploader details are not shown here.",online:"Online",offline:"Offline",on:"ON",off:"OFF",paused:"Paused",running:"Open",pause:"Pause",resume:"Resume",empty:"No games are waiting.",waiting:"Waiting for operator",sent:"Released to cartridge",claimed:"Cartridge receiving",downloaded:"Switching",deferred:"Waiting for safe state",cancel:"Cancel",cancelConfirm:"Cancel this entry?",advanceDone:"Released one game to the cartridge.",actionError:"Could not complete the action. Refresh and check the current state.",authError:"Check your operator token.",networkError:"Could not connect. Try again later."}};
    copy.ja.waitingHelp="ROM本体は表示しません。お名前とコメントは展示スタッフだけに表示されます。";
    copy.en.waitingHelp="ROM bytes are not shown. Names and comments are visible to exhibition staff only.";
    copy.ja.nameLabel="お名前";copy.en.nameLabel="Name";
    copy.ja.commentLabel="コメント";copy.en.commentLabel="Note";
    Object.assign(copy.ja,{galleryTitle:"公開ギャラリー",galleryHelp:"掲載だけを取り下げます。受付済みのROMやプレイ待ちは取り消しません。",galleryEmpty:"公開中の作品はありません。",withdraw:"掲載を取り下げる",withdrawConfirm:"この作品をギャラリーから取り下げますか？ ROMの受付は残ります。"});
    Object.assign(copy.en,{galleryTitle:"Public gallery",galleryHelp:"Withdraw only the listing. The ROM submission and play queue remain.",galleryEmpty:"No public games are listed.",withdraw:"Withdraw listing",withdrawConfirm:"Remove this game from the gallery? Its ROM submission will remain."});
    let lang="ja",token="",timer=null,lastStatus=null,lastQueue=[],lastGallery=[];
    const el=id=>document.getElementById(id),t=key=>copy[lang][key]||key;
    function setLang(next){lang=next;document.documentElement.lang=next;document.title="Famicom Game Drop | "+(next==="ja"?"管理者":"Operator");document.querySelectorAll("[data-t]").forEach(node=>node.textContent=t(node.dataset.t));el("ja").setAttribute("aria-pressed",String(next==="ja"));el("en").setAttribute("aria-pressed",String(next==="en"));render();renderGallery();}
    el("ja").onclick=()=>setLang("ja");el("en").onclick=()=>setLang("en");
    function request(path,method="GET",body){return fetch(path,{method,headers:{Authorization:"Bearer "+token,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,cache:"no-store"});}
    function render(){if(!lastStatus)return;const s=lastStatus,d=s.device,online=d&&Date.now()/1000-d.last_seen_at<30;el("device").textContent=t(online?"online":"offline");el("power").textContent=d?t(d.console_power?"on":"off"):"—";el("queueCount").textContent=String(lastQueue.filter(j=>j.state==="queued"&&j.released_at===null).length);el("runState").textContent=t(s.paused?"paused":"running");el("pause").textContent=t(s.paused?"resume":"pause");const active=lastQueue.some(j=>j.released_at!==null);el("advance").disabled=s.paused||active||!lastQueue.some(j=>j.state==="queued"&&j.released_at===null);const list=el("queue");list.replaceChildren();if(!lastQueue.length){const p=document.createElement("p");p.className="muted";p.textContent=t("empty");list.append(p);}for(const job of lastQueue){const row=document.createElement("div"),text=document.createElement("p"),detail=document.createElement("small");row.className="queue-item";const state=job.state==="queued"?(job.released_at===null?"waiting":"sent"):job.state;const local=new Date(job.created_at*1000).toLocaleTimeString(lang==="ja"?"ja-JP":"en-US",{hour:"2-digit",minute:"2-digit"});text.textContent=job.id.slice(0,8)+" · "+t(state);detail.textContent=local+" · Mapper "+job.mapper+" · PRG "+job.prg_kib+" KiB";const block=document.createElement("div");block.append(text,detail);if(job.author_name){const name=document.createElement("p");name.textContent=t("nameLabel")+": "+job.author_name;block.append(name);}if(job.visitor_comment){const note=document.createElement("p");note.textContent=t("commentLabel")+": "+job.visitor_comment;block.append(note);}row.append(block);if(job.state==="queued"){const cancel=document.createElement("button");cancel.type="button";cancel.textContent=t("cancel");cancel.onclick=()=>cancelJob(job.id);row.append(cancel);}list.append(row);}}
    function renderGallery(){const list=el("galleryQueue");list.replaceChildren();if(!lastGallery.length){const empty=document.createElement("p");empty.className="muted";empty.textContent=t("galleryEmpty");list.append(empty);return;}for(const item of lastGallery){const row=document.createElement("div"),title=document.createElement("p"),button=document.createElement("button");row.className="queue-item";title.textContent=item.title;button.type="button";button.textContent=t("withdraw");button.onclick=()=>withdrawGallery(item.id);row.append(title,button);list.append(row);}}
    async function refresh(){if(!token)return;try{const [s,q,g]=await Promise.all([request("/api/operator/status"),request("/api/operator/queue"),request("/api/operator/gallery")]);if(s.status===401||q.status===401||g.status===401){token="";el("dashboard").hidden=true;el("login").hidden=false;el("loginError").textContent=t("authError");el("loginError").hidden=false;return;}if(!s.ok||!q.ok||!g.ok)throw Error();lastStatus=await s.json();lastQueue=(await q.json()).jobs;lastGallery=(await g.json()).items;el("loginError").hidden=true;el("login").hidden=true;el("dashboard").hidden=false;render();renderGallery();}catch(_){if(el("login").hidden){el("actionFeedback").textContent=t("networkError");}else{el("loginError").textContent=t("networkError");el("loginError").hidden=false;}}}
    async function act(path,body){el("actionFeedback").textContent="";try{const response=await request(path,"POST",body);if(!response.ok)throw Error();await refresh();return true;}catch(_){el("actionFeedback").textContent=t("actionError");await refresh();return false;}}
    async function cancelJob(id){if(confirm(t("cancelConfirm")))await act("/api/operator/jobs/"+id+"/cancel");}
    async function withdrawGallery(id){if(confirm(t("withdrawConfirm")))await act("/api/operator/gallery/"+id+"/withdraw");}
    el("loginForm").onsubmit=async event=>{event.preventDefault();token=el("token").value;el("token").value="";await refresh();clearInterval(timer);timer=setInterval(refresh,3000);};
    el("refresh").onclick=refresh;el("advance").onclick=async()=>{if(await act("/api/operator/advance"))el("actionFeedback").textContent=t("advanceDone");};el("pause").onclick=()=>act("/api/operator/pause",{paused:!lastStatus.paused});
  </script>
</body>
</html>`;
